#!/usr/bin/env python3
"""
Data Analysis Calculator
Calculator optimized for data analysis tasks

Generated by Calculator Generator
Author: Calculator Generator
Version: 1.0.0
Generated: 2025-07-20 15:52:31
"""

import sys
import os
import math
import numpy as np
import pandas as pd



def add(a, b):
    """Addition operation"""
    return a + b


def subtract(a, b):
    """Subtraction operation"""
    return a - b


def multiply(a, b):
    """Multiplication operation"""
    return a * b


def divide(a, b):
    """Division operation"""
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b


def power(a, b):
    """Power operation"""
    return a ** b


def modulo(a, b):
    """Modulo operation"""
    if b == 0:
        raise ValueError("Cannot calculate modulo with zero")
    return a % b


def mean(data):
    """Calculate mean of data"""
    return np.mean(data)


def median(data):
    """Calculate median of data"""
    return np.median(data)


def std(data):
    """Calculate standard deviation"""
    return np.std(data)


def variance(data):
    """Calculate variance"""
    return np.var(data)


def correlation(x, y):
    """Calculate correlation coefficient"""
    return np.corrcoef(x, y)[0, 1]



class Calculator:
    """Main calculator class"""

    def __init__(self):
        self.precision = 10
        self.angle_unit = "degrees"

    def format_result(self, result):
        """Format calculation result"""
        if isinstance(result, (int, float)):
            return round(result, self.precision)
        return result

    def run(self):
        """Run the calculator interface"""
        self.show_banner()
        self.interactive_mode()

    def interactive_mode(self):
        """Interactive calculator mode"""
        print("Calculator started. Type 'help' for commands, 'quit' to exit.")

        while True:
            try:
                user_input = input("calc> ").strip()

                if user_input.lower() in ['quit', 'exit', 'q']:
                    break
                elif user_input.lower() == 'help':
                    self.show_help()
                elif user_input.lower() == 'clear':
                    os.system('cls' if os.name == 'nt' else 'clear')
                else:
                    result = self.evaluate_expression(user_input)
                    formatted_result = self.format_result(result)
                    print(f"Result: {formatted_result}")

            except KeyboardInterrupt:
                print("\nGoodbye!")
                break
            except Exception as e:
                print(f"Error: {e}")

    def show_banner(self):
        """Display calculator banner"""
        print("="*50)
        print(f"  Data Analysis Calculator")
        print(f"  Calculator optimized for data analysis tasks")
        print("="*50)

    def show_help(self):
        """Display help information"""
        help_text = """
Available commands:
  Basic operations: +, -, *, /, **, %
  Functions: sin(), cos(), tan(), log(), ln(), sqrt()
  Other: help, clear, quit
        """
        print(help_text)

    def evaluate_expression(self, expression):
        """Evaluate mathematical expression"""
        # Basic expression evaluation
        try:
            # Replace common functions
            expression = expression.replace('^', '**')
            
            # Add math functions to evaluation context
            safe_dict = {
                "__builtins__": {},
                "abs": abs, "round": round, "min": min, "max": max,
                "sqrt": math.sqrt, "pi": math.pi, "e": math.e
            }
            safe_dict.update({
                "np": np, "array": np.array, "mean": mean,
                "median": median, "std": std
            })

            return eval(expression, safe_dict)
        except Exception as e:
            raise ValueError(f"Invalid expression: {e}")


if __name__ == "__main__":
    calculator = Calculator()
    calculator.run()
