#!/usr/bin/env python3
"""
Scientific Calculator
Full-featured scientific calculator

Generated by Calculator Generator
Author: Calculator Generator
Version: 1.0.0
Generated: 2025-07-20 15:52:09
"""

import sys
import os
import math
import numpy as np
import scipy as sp
from scipy import stats, optimize, integrate



def add(a, b):
    """Addition operation"""
    return a + b


def subtract(a, b):
    """Subtraction operation"""
    return a - b


def multiply(a, b):
    """Multiplication operation"""
    return a * b


def divide(a, b):
    """Division operation"""
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b


def power(a, b):
    """Power operation"""
    return a ** b


def modulo(a, b):
    """Modulo operation"""
    if b == 0:
        raise ValueError("Cannot calculate modulo with zero")
    return a % b


def sin(x, angle_unit="degrees"):
    """Sine function"""
    if angle_unit == "degrees":
        x = math.radians(x)
    return math.sin(x)


def cos(x, angle_unit="degrees"):
    """Cosine function"""
    if angle_unit == "degrees":
        x = math.radians(x)
    return math.cos(x)


def tan(x, angle_unit="degrees"):
    """Tangent function"""
    if angle_unit == "degrees":
        x = math.radians(x)
    return math.tan(x)


def asin(x, angle_unit="degrees"):
    """Arcsine function"""
    result = math.asin(x)
    if angle_unit == "degrees":
        result = math.degrees(result)
    return result


def acos(x, angle_unit="degrees"):
    """Arccosine function"""
    result = math.acos(x)
    if angle_unit == "degrees":
        result = math.degrees(result)
    return result


def atan(x, angle_unit="degrees"):
    """Arctangent function"""
    result = math.atan(x)
    if angle_unit == "degrees":
        result = math.degrees(result)
    return result


def log(x, base=10):
    """Logarithm function"""
    if x <= 0:
        raise ValueError("Logarithm input must be positive")
    if base == math.e:
        return math.log(x)
    return math.log(x, base)


def ln(x):
    """Natural logarithm"""
    if x <= 0:
        raise ValueError("Natural logarithm input must be positive")
    return math.log(x)


def log10(x):
    """Base-10 logarithm"""
    if x <= 0:
        raise ValueError("Logarithm input must be positive")
    return math.log10(x)


def log2(x):
    """Base-2 logarithm"""
    if x <= 0:
        raise ValueError("Logarithm input must be positive")
    return math.log2(x)


def mean(data):
    """Calculate mean of data"""
    return np.mean(data)


def median(data):
    """Calculate median of data"""
    return np.median(data)


def std(data):
    """Calculate standard deviation"""
    return np.std(data)


def variance(data):
    """Calculate variance"""
    return np.var(data)


def correlation(x, y):
    """Calculate correlation coefficient"""
    return np.corrcoef(x, y)[0, 1]


def matrix_multiply(a, b):
    """Matrix multiplication"""
    return np.dot(a, b)


def matrix_inverse(matrix):
    """Matrix inverse"""
    return np.linalg.inv(matrix)


def matrix_determinant(matrix):
    """Matrix determinant"""
    return np.linalg.det(matrix)


def eigenvalues(matrix):
    """Calculate eigenvalues"""
    return np.linalg.eigvals(matrix)



class Calculator:
    """Main calculator class"""

    def __init__(self):
        self.precision = 15
        self.angle_unit = "radians"

    def format_result(self, result):
        """Format calculation result"""
        if isinstance(result, (int, float)):
            return round(result, self.precision)
        return result

    def run(self):
        """Run the calculator interface"""
        self.show_banner()
        self.interactive_mode()

    def interactive_mode(self):
        """Interactive calculator mode"""
        print("Calculator started. Type 'help' for commands, 'quit' to exit.")

        while True:
            try:
                user_input = input("calc> ").strip()

                if user_input.lower() in ['quit', 'exit', 'q']:
                    break
                elif user_input.lower() == 'help':
                    self.show_help()
                elif user_input.lower() == 'clear':
                    os.system('cls' if os.name == 'nt' else 'clear')
                else:
                    result = self.evaluate_expression(user_input)
                    formatted_result = self.format_result(result)
                    print(f"Result: {formatted_result}")

            except KeyboardInterrupt:
                print("\nGoodbye!")
                break
            except Exception as e:
                print(f"Error: {e}")

    def show_banner(self):
        """Display calculator banner"""
        print("="*50)
        print(f"  Scientific Calculator")
        print(f"  Full-featured scientific calculator")
        print("="*50)

    def show_help(self):
        """Display help information"""
        help_text = """
Available commands:
  Basic operations: +, -, *, /, **, %
  Functions: sin(), cos(), tan(), log(), ln(), sqrt()
  Other: help, clear, quit
        """
        print(help_text)

    def evaluate_expression(self, expression):
        """Evaluate mathematical expression"""
        # Basic expression evaluation
        try:
            # Replace common functions
            expression = expression.replace('^', '**')
            
            # Add math functions to evaluation context
            safe_dict = {
                "__builtins__": {},
                "abs": abs, "round": round, "min": min, "max": max,
                "sqrt": math.sqrt, "pi": math.pi, "e": math.e
            }
            safe_dict.update({
                "sin": lambda x: sin(x, self.angle_unit),
                "cos": lambda x: cos(x, self.angle_unit),
                "tan": lambda x: tan(x, self.angle_unit),
                "asin": lambda x: asin(x, self.angle_unit),
                "acos": lambda x: acos(x, self.angle_unit),
                "atan": lambda x: atan(x, self.angle_unit)
            })
            safe_dict.update({
                "log": log, "ln": ln, "log10": log10, "log2": log2
            })
            safe_dict.update({
                "np": np, "array": np.array, "mean": mean,
                "median": median, "std": std
            })

            return eval(expression, safe_dict)
        except Exception as e:
            raise ValueError(f"Invalid expression: {e}")


if __name__ == "__main__":
    calculator = Calculator()
    calculator.run()
